### ISSUE TITLE
微信小程序用户隐私ts方法提示

### ISSUE THREAD

**Issue by modushanghai** [uni-helper/uni-app-snippets-vscode#16]
### 对问题的清晰和简明的描述

没有微信小程序用户隐私方法提示 
uni.getPrivacySetting
uni.openPrivacyContract

### 推荐的解决方案

微信小程序增加ts类型
uni.getPrivacySetting
uni.openPrivacyContract

### 检查

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个要求相同功能的问题，以避免重复创建。

**Comment by ModyQyW** [comment]
请问你是需要 ts 类型还是代码片段？

**Comment by modushanghai** [comment]
> 请问你是需要 ts 类型还是代码片段？

ts类型   ，不然的话vscode会报红 
![image](https://github.com/uni-helper/uni-app-snippets-vscode/assets/71951170/aea86d0e-b860-47f7-90a7-c33584a0ac46)

**Comment by ModyQyW** [comment]
那应该到 uni-app 开 issue 提出更新 @dcloudio/types，这个仓库不负责这一类 ts 类型，谢谢。
