### ISSUE TITLE
建议新增代码提示自定义配置功能

### ISSUE THREAD

**Issue by cooper1x** [uni-helper/uni-app-snippets-vscode#20]
### 对问题的清晰和简明的描述

![image](https://github.com/user-attachments/assets/4f3826b1-78cb-4064-ae1f-58abfb21cd01)
这么多平台我都用不上，我只是想写个css的border，这个代码提示影响我正常开发了。

### 推荐的解决方案

可以手动配置代码提示，可以删掉不需要的代码提示，或者改下优先级也可以。

### 检查

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个要求相同功能的问题，以避免重复创建。

**Comment by ModyQyW** [comment]
禁用插件，或者自己写 snippets，或者 fork 自己改。你所推荐的解决方案都不是这个插件可以做到的，也不是这个插件应该做的，请自行处理，谢谢。
